name: Integration Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow:
    uses: microsoft/triton-shared/.github/workflows/test-plugin.yml@v1
    with:
        triton-ref: '215b2e77a1d92f907bc4addfa3c3ba204028c32e' # known good commit "Add Shared Middle Layer to Triton via Plug-In"     
        triton-shared-ref: ${{ github.ref }}